version: '3.5'

services:
  yobetit-app:
    image: yobetit-app:prod
    environment:
      PG_HOST: postgres
      PG_PORT: 5432
      DATABASE_URL: postgres://fsktrgdkktmcbt:e7929351d7a362df38f1c6b1ff7139b79e0e781f9340c38e15709c490807e7ba@ec2-35-175-155-248.compute-1.amazonaws.com:5432/dcrivnlgr817pn
    build: 
      context: .
      target: prod
    container_name: yobetit-app
    restart: always
    volumes: 
      - .:/app
    ports:
      - "80:3000"
    depends_on:
      - postgres
    networks: 
      - yobetit-app-network
  postgres:
    container_name: postgres-db
    image: postgres:12
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "55432:5432"
    networks:
      - yobetit-app-network
    restart: unless-stopped

  pgadmin:
    container_name: postgres-db-pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "50080:80"
    networks:
      - yobetit-app-network
    restart: unless-stopped

networks:
  yobetit-app-network:
    driver: bridge

volumes:
  postgres:
  pgadmin: